== System Specification

[[system_general]]
=== General Principles and System Description Terms

This section will give an introduction to the terminology and principles
for system modelling in `RIFLEX`.

The system definition starts with definition of the topology and
proceeds in increasing detail to the line and component descriptions. It
is possible to specify a system with general topology (Arbitrary Riser
System, AR), but several alternatives are also available for simplified
input of commonly used configurations with well defined standard
topologies (e.g. standard system SA, SB, SD, SC). The line- and
component specifications will, in most cases, be independent of the
system topology (see the figure `System definition INPMOD' below). There
are, however, a few component types available for the arbitrary system
that can not be used in standard systems, see
link:@ref%20system_general_component[Component Description].

[[system_general_system]]
==== System Topology Description

The system topology is in general described in terms of branching points
and terminal points. These points are denoted supernodes. Supernodes are
connected by simple lines. This means that the system topology is
uniquely determined by the connectivity between a number of defined
supernodes and lines.

A general supernode/line connectivity can be specified for arbitrary
systems while a restricted system specific connectivity is available for
standard systems.

[[system_general_boundary]]
==== Boundary Condition Modelling at Supernodes

Supernodes are classified as free, fixed or prescribed depending on
their boundary condition modelling. A supernode is denoted free if all
degrees of freedom are free (i.e. nodal position and rotations are
unknown prior to the analysis). In modelling of standard systems it is
further distinguished between free branchings (`TSNBRA`) and free ends
(`TSNFRE`) to ease system topology description.

Supernodes of type fixed are used for modelling supports at fixed
structures, seafloor connection, etc. A supernode is denoted fixed if
one or several degrees of freedom (dof’s) are fixed. For arbitrary
systems it is possible to specify status code free/fixed for all degrees
of freedom for each supernode of type fixed (i.e. status code
specifications for global x, y, z translations and rotations). For
standard systems, all dof’s of fixed supernodes are assumed fixed
(rotation free support can still be specified using the ``connector''
component).

Prescribed supernodes are normally used for modelling supports with
forced (prescribed) dynamic motions (e.g. connections to floating
support vessels).

The interpretations/specifications are similar to fixed supernodes.

System definition INPMOD

[[system_general_specification]]
==== Specification of Supernode Positions for Stressfree and Final Configurations

The basis for calculation of structural forces and deformations in
finite element analysis is a stressfree reference configuration defining
the state of no structural forces/deformations. A stressfree
configuration for structural parts with bending stiffness and no initial
deformations will always be a straight line.

The stressfree configuration for arbitrary systems is therefore
specified on system level by specification of stressfree positions
(global x, y and z-coordinates) of all supernodes. Stressfree position
of intermediate `FEM` nodes are then computed by the program assuming a
straight line configuration between stressfree supernode positions. The
stressfree configurations for standard systems are automatically
generated by the program, see link:@ref%20system_standard[Standard
Systems] for a description. Output of generated stressfree
configurations are optionally available in `STAMOD`.

Final static position of relevant dof’s for fixed and prescribed
supernodes are specified as a part of the system description.

[[system_general_line]]
==== Line and Segment Description

A line is a linear structural element between two supernodes which is
identified by a line type number. This means that a line type can be
referred to several times in the system topology description, which is
convenient for modelling of systems with several identical lines (e.g.
anchor systems).

===== The line is specified in terms of:

* Sequence of segments with homogeneous cross sectional properties.
Cross sectional component type, length and number of elements to be used
for finite element discretization are specified for each segment (see
`System definition terms' (below)).
* Nodal components for modeling of clump weights, buoys, swivels and
hinges etc. can be specified at segment intersections.
* Fluid component (`FLUID`) for description of possible internal fluid
flow.

System definition terms

* `SUPERNODE`: Branching points or nodes with specified boundary
conditions.
* `LINE`: Suspended structure between two supernodes.
* `SEGMENT`: (Part of) line with uniform cross section properties and
element length.
* `ELEMENT`: Finite element unit.

[[system_general_component]]
==== Component Description

The components represents the elementary description of the mechanical
properties. A component is identified by a numerical identifier called
component type number.

The components available in present `RIFLEX` version are:

[arabic]
. Cross sectional components

* Pipe cross section (`CRS0`)
* Axi-symmetric cross section (`CRS1`)
* Bi-symmetric cross section (`CRS2`)
* Cross section for advanced modelling of floating, partly submerged
structures, either axi-symmetric or bi-symmetric (`CRS3`, `CRS4`,
`CRS5`). Only available for ``arbitrary'' systems.
* General non-symmetric cross section (`CRS7`)

Cross sectional stiffness properties are specified in terms of axial
and, optionally, bending and torsional stiffness. Elements specified
with axial stiffness only are represented by 3D bar elements. Elements
with specified bending and torsional stiffness are represented by 3D
beam elements. Linear or nonlinear stiffness specifications can be
applied for all cross sectional types.

Additional data that must be specified for all cross sectional types are
external and internal area, mass and hydrodynamical coefficients.

A special component denoted external wrapping (`EXT1`) is also available
for modelling additional distributed weight or buoyancy.

[arabic, start=2]
. Nodal components

* Body (`BODY`) for modelling of clump weight, submerged buoys etc.
* Ball joint connector (`CONB`) for modelling of swivels, hinges etc.

Mass, volume and hydrodynamical coefficients must be specified for both
component types.

[arabic, start=3]
. Special components

* Rollers for description of elastic contact forces between lines.
* Tensioner component for modelling of tensioner mechanisms.

[[system_general_element]]
==== Element Mesh Generation

The element mesh is computed automatically based on the topology, line
and component description. Constant element lengths are applied within
segments. Connections between lines, segments and elements specified as
input and nodal/element numbers used in the finite element analysis are
available as output from `STAMOD`.

[[system_standard]]
=== Standard Systems

[[system_standard_classification]]
==== Classification

In order to simplify the system topology definition for commonly used
configurations, a selection of standard systems are provided:

* SA - Seafloor to surface vessel. One point seafloor contact. The Steep
Wave, Steep S and Jumper flexible riser configurations are special cases
of the SA system.
* SB - Seafloor to surface vessel. Seafloor tangent and/or additional
seafloor attachment point. The Lazy Wave and Lazy S flexible riser
configurations are special cases of the SB system. The SB system is also
convenient for modelling of anchorlines with seafloor contact at lower
end.
* SC - Free lower end. Riser during installation etc.
* SD - Free upper end. Buoyed riser, loading system, etc.

The stressfree configurations are automatically generated for all
standard systems. Definition of system topologies and stressfree
configurations are further discussed in the remaining sections of this
chapter (```SA'' Seafloor to Surface Vessel, One-Point Seafloor Contact'
to ```SD'' Free Upper End').

===== Global coordinate systems

The x-y plane of the global coordinate system is placed at the sea
surface with the z-axis pointing upwards.

The following conventions are in addition adopted for the standard riser
systems:

* Boundary conditions, i.e. terminal point coordinates are specified in
x-z plane
* x-coordinate at lower end is zero for SA, SB and SD systems
* x-coordinate at upper end is zero for SC systems

The global coordinate systems for all standard systems are shown in
figures presented in the remaining sections of this chapter (```SA''
Seafloor to Surface Vessel, One-Point Seafloor Contact' to ```SD'' Free
Upper End').

===== Special analysis features

An important feature available for standard systems is simplified static
analysis based on catenary analysis. It is also possible to use the
catenary solution as starting point for the static finite element
analysis or to apply conventional finite element analysis starting from
stressfree position.

For further details, see `Static Catenary Analysis' and `Static Finite
Element Analysis' in the Theory Manual.

[[system_standard_sa]]
==== ``SA'' Seafloor to Surface Vessel, One-Point Seafloor Contact

Examples of configurations covered by SA

===== System topology

The riser is suspended between two defined points. The lower end is
fixed while upper end is connected to the support vessel. The only type
of branching elements are slender buoyancy or weight elements suspended
in one-point attachment. Only one branch is accepted per branch node.
The branches are thus assumed to be vertical in a zero current
condition.

===== Stressfree configuration

The stressfree configuration is placed horizontally at seafloor,
branches are assumed vertical.

Example of stressfree configuration for SA system

[[system_standard_sb]]
==== ``SB'' Seafloor to Surface Vessel, Seafloor Tangent

Examples of configurations covered by SB

===== System topology

Compared with the previous systems this system includes additional
features:

* Seafloor tangent boundary condition
* Buoyancy guide at one point

The seafloor contact is modelled by bilinear stiffness. The stiffness is
discretized and implemented as springs at the nodal points that may
touch the seafloor.

===== Stressfree configuration

The stressfree configuration is placed horizontally. The vertical
position is placed above the seafloor to avoid possible seafloor contact
at the first steps in the incremental loading sequence applied in the
static finite element analysis. Possible branches are assumed vertical.

Examples of stressfree configuration for SB systems

[[system_standard_sc]]
==== ``SC'' Free Lower End, Suspended from Surface Vessel

Examples of configurations covered by SC

===== System topology

This group is characterized by a free lower end, all degrees of freedom
being specified at the upper end. This configuration represents typical
installation phases, but as indicated in the figure, towing
configurations can be analyzed as well.

===== Stressfree configuration

The stressfree configuration is assumed vertical with vertical position
of upper end equal to final position.

[[system_standard_sd]]
==== ``SD'' Free Upper End

===== System topology

Single line system connected to seafloor at lower end and with free
upper end.

===== Stressfree configuration

The stressfree configuration is assumed vertical with lower end in final
position (e.g. at seafloor).

Examples of configurations covered by SD

With a free upper end the configuration is governed by hydrodynamic
forces in the horizontal direction. If the buoyancy element is
surface-piercing, it is assumed that it is a long, slender, spar-type
buoy.
